[project]
name = "mcp-calculator"
version = "0.1.0"
description = "A simple MCP compliant client and server to understand MCP basics"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.49.0",
    "async-exit-stack>=1.0.1",
    "fastmcp>=2.2.0",
    "mcp>=1.6.0",
]
